name: csms-event-service

services:
  event_postgres:
    image: postgres:16
    container_name: event-postgres
    environment:
      POSTGRES_USER: event_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: event_db
    ports:
      - "5432:5432"
    volumes:
      - event_pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - csms-event-service-network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    restart: unless-stopped
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - csms-event-service-network

  kafka:
    image: wurstmeister/kafka:latest
    restart: unless-stopped
    environment:
      KAFKA_LOG_DIRS: /kafka-data
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: EXTERNAL://:9092,INTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://127.0.0.1:9092,INTERNAL://kafka:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CREATE_TOPICS: >
        event_created:1:1,
        seat_booked:1:1,
        venue_created:1:1
    depends_on:
      - zookeeper
    networks:
      - csms-event-service-network
    volumes:
      - csms-kafka-data:/kafka-data
    ports:
      - '9092:9092'
  
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    restart: unless-stopped
    depends_on:
      - kafka
    networks:
      - csms-event-service-network
    ports:
      - "8003:8080"
    volumes:
      - ./schemas:/schemas
    environment:
      kafka.clusters.0.name: kafka
      kafka.clusters.0.bootstrapServers: kafka:9094
      kafka.clusters.0.defaultKeySerde: ProtobufFile
      kafka.clusters.0.defaultValueSerde: ProtobufFile

      kafka.clusters.0.serde.0.name: ProtobufFile
      kafka.clusters.0.serde.0.properties.protobufFilesDir: /schemas/

      kafka.clusters.0.serde.0.properties.protobufMessageNameForKeyByTopic.event_created: analytics.EventCreatedKey
      kafka.clusters.0.serde.0.properties.protobufMessageNameByTopic.event_created: analytics.EventCreatedValue
      kafka.clusters.0.serde.0.properties.protobufMessageNameForKeyByTopic.seat_booked: analytics.SeatsBookedKey
      kafka.clusters.0.serde.0.properties.protobufMessageNameByTopic.seat_booked: analytics.SeatsBookedValue
      kafka.clusters.0.serde.0.properties.protobufMessageNameForKeyByTopic.venue_created: analytics.VenueCreatedKey
      kafka.clusters.0.serde.0.properties.protobufMessageNameByTopic.venue_created: analytics.VenueCreatedValue

networks:
  csms-event-service-network:
    driver: bridge

volumes:
  event_pgdata: {}
  csms-kafka-data: {}